apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-policy
  namespace: security
  labels:
    app: trivy

data:
  policy.rego: |
    package main
    deny[msg] {
      input.Image.Tag == "latest"
      msg = "Disallow usage of 'latest' tag."
    }
    deny[msg] {
      input.Image.Privileged == true
      msg = "Privileged containers are prohibited."
    }
    deny[msg] {
      cve := input.Vulnerabilities[_]
      cve.Severity == "CRITICAL"
      msg = sprintf("Critical CVE %s found in %s", [cve.ID, input.Image.Name])
    }
