apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:sre-admin, applications, *, */*, allow
    p, role:sre-admin, clusters, *, *, allow
    p, role:sre-admin, projects, *, *, allow
    p, role:sre-admin, repositories, *, *, allow
    p, role:sre-admin, exec, *, *, allow

    p, role:dev-deployer, applications, create, dev/*, allow
    p, role:dev-deployer, applications, update, dev/*, allow
    p, role:dev-deployer, applications, delete, dev/*, allow
    p, role:dev-deployer, applications, sync, dev/*, allow
    p, role:dev-deployer, applications, get, dev/*, allow

    g, sre-team, role:sre-admin
    g, dev-team, role:dev-deployer
  scopes: '[groups, email]'
