{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "payment-service.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "payment-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "payment-service.selectorLabels" . | nindent 6 }}
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
