apiVersion: v1
kind: Secret
metadata:
  name: frontend-service-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "frontend-service.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
data:
  {{- if .Values.envFrom }}
  {{- range .Values.envFrom }}
  {{- if .secretRef }}
  {{- end }}
  {{- end }}
  {{- end }}
  API_KEY: ""
  DB_PASSWORD: ""
